#define user in AWS with programmatic access 'y'
#add policy to this user of type: AmazonEC2ContainerRegistryPowerUser
#save the Access key ID and Secret Access Key displayed at the End
#add these variables to the gitlab project:
#project>>settings>>variables 
#AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY

variables:
     DOCKER_REGISTRY: 504147157645.dkr.ecr.us-east-1.amazonaws.com
     AWS_DEFAULT_REGION: us-east-1
     APP_NAME: IVI2SRE
     DOCKER_HOST: tcp://docker:2375
publish:
    image: 
      name: amazon/aws-cli
      entrypoint: [""]
    service:
        - docker:dind
    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version		
    script:
        - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
        - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
        - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID