name: Deploy Bundle to Databricks
on:
  workflow_dispatch:
jobs:          
  deploy_bundle:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Databricks CLI config
          run: |
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh            
        - name: Databricks token config
          run: |
            databricks configure --token <<EOF ${{ vars.DATABRICKS_HOST_URL }} ${{ secrets.DATABRICKS_DEV_TOKEN }}  EOF
        - name: Deploy Bundle
          env:
           DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
           WORKSPACE_ENV: dev
          run: |
            databricks bundle validate -t dev
            databricks bundle deploy -t dev
