name: Deploy Notebook & Bundle to Databricks
on:
  workflow_dispatch:

env:
  DATABRICKS_HOST_URL: https://dbc-68d2f873-1a1e.cloud.databricks.com/
  FILE_NAME_TO_DEPLOY: test1.py
  DEPLOY_FOLDER: /Users/kletnoi@live.com/testing/

jobs:
  deploy_notebook:
    environment: 
      name: vars
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            # curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh          
            
      - name: Databricks token config
        run: |        
            # databricks configure --token <<EOF
            # ${{ vars.DATABRICKS_HOST_URL }}
            # ${{ secrets.DATABRICKS_DEV_TOKEN }}
            # EOF
            
      - name: Deploy code to databricks workspace
        run: |
            #databricks workspace import notebooks/${{ env.FILE_NAME_TO_DEPLOY }} ${{ env.DEPLOY_FOLDER }}${{ env.FILE_NAME_TO_DEPLOY }} -l python --overwrite
            
            
  next_step:
      needs: deploy_notebook
      runs-on: ubuntu-latest

      steps:
        - name: Deploy Bundle
          env:
           DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}       
          run: |
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
            databricks bundle validate -t dev
            databricks bundle deploy -t dev

