name: Deploy Notebook to Databricks
on:
  workflow_dispatch:

jobs:
  push_to_db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            pip install databricks-cli 
            cat > ~/.databrickscfg << EOF 
            [DEFAULT]
            host = https://dbc-68d2f873-1a1e.cloud.databricks.com/
            jobs-api-version = 2.0
            token = dapi8b2754011c4da8f14a50b144f4611477
            EOF 
    
      - name: Deploy code to databricks workspace
        run: |
            databricks workspace import ${{ inputs.service_code_file }} ${{ inputs.databricks_code_path }} --language python --overwrite
