name: Deploy Bundle to Databricks
on:
  workflow_dispatch:
jobs:          
  deploy_bundle:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Bundle
          env:
           DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
           WORKSPACE_ENV: dev
          run: |
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
            databricks bundle validate -t dev
            databricks bundle deploy -t dev
