name: Notebook Deployment - Databricks
on:
  workflow_dispatch:
    inputs:
      databricks_code_path:
        description: /Shared/test1.py
        type: string
        required: true
      service_code_file:
        description: ./notebooks/test1.py
        type: string
        required: true
      databricks_host_url:
        description: https://dbc-68d2f873-1a1e.cloud.databricks.com/
        type: string
        required: true
        

jobs:
  push_to_db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            pip install databricks-cli 
            cat > ~/.databrickscfg << EOF 
            [DEFAULT] 
            host = ${{ inputs.databricks_host_url }} 
            token = ${{ secrets.DATABRICKS_TOKEN }} 
            jobs-api-version = 2.1 
            EOF 
    
      - name: Deploy code to databricks workspace
        run: |
            databricks workspace import ${{ inputs.service_code_file }} ${{ inputs.databricks_code_path }} --language python --overwrite
